# -*- coding: utf-8 -*-
"""
CLOUD AGENT EXECUTOR
====================

Purpose:
    - Receives orchestrator call from local agent
    - Runs orchestrator.py end-to-end
    - Executes all pipeline steps (ETL → QA → Viz → HTML → MP4 → GIF → Publish → Verify)
    - Returns structured results to local agent
    - Local agent runs final verification

Role: Executor + Publisher

Author: OpenClaw Cloud Agent
Date: 5 Mar 2026
"""

import json
import subprocess
import traceback
from pathlib import Path
from datetime import datetime
from typing import Dict, Any
import sys


# ========================================================================
# ORCHESTRATOR EXECUTOR — Runs the full pipeline
# ========================================================================

class OrchestratorExecutor:
    """
    Executes orchestrator.py end-to-end.
    Captures all outputs and returns results.
    """

    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.orchestrator_script = project_root / "scripts" / "orchestrator.py"

    def run_orchestrator(self) -> Dict:
        """
        Execute the orchestrator and capture results.
        
        Returns:
            Dict with execution status and outputs
        """
        print("[CLOUD] Executing orchestrator.py...")

        if not self.orchestrator_script.exists():
            return {
                "status": "failed",
                "error": f"Orchestrator not found: {self.orchestrator_script}",
            }

        try:
            # Run orchestrator in subprocess
            result = subprocess.run(
                [sys.executable, str(self.orchestrator_script)],
                cwd=str(self.project_root),
                capture_output=True,
                text=True,
                timeout=600,  # 10 minute timeout
            )

            if result.returncode == 0:
                print("[CLOUD] Orchestrator completed successfully")
                return {
                    "status": "success",
                    "stdout": result.stdout,
                    "stderr": result.stderr,
                    "return_code": 0,
                }
            else:
                print(f"[CLOUD] Orchestrator failed with return code {result.returncode}")
                return {
                    "status": "failed",
                    "stdout": result.stdout,
                    "stderr": result.stderr,
                    "return_code": result.returncode,
                }

        except subprocess.TimeoutExpired:
            return {
                "status": "timeout",
                "error": "Orchestrator execution exceeded 600s timeout",
            }
        except Exception as e:
            return {
                "status": "error",
                "error": str(e),
                "traceback": traceback.format_exc(),
            }


# ========================================================================
# OUTPUT COLLECTOR — Gathers all pipeline outputs
# ========================================================================

class OutputCollector:
    """
    Collects all outputs generated by the orchestrator.
    """

    def __init__(self, project_root: Path):
        self.project_root = project_root

    def collect_outputs(self) -> Dict[str, Dict]:
        """
        Scan project directories for outputs created by orchestrator.
        
        Returns:
            Dict mapping output type → file info
        """
        outputs = {}

        # Define expected output locations
        output_locations = {
            "html": self.project_root / "reports" / "html",
            "mp4": self.project_root / "reports" / "media",
            "gif": self.project_root / "reports" / "media",
            "csv": self.project_root / "csv" / "processed",
            "qa_reports": self.project_root / "reports" / "qa",
            "logs": self.project_root / "reports" / "logs",
        }

        for output_type, directory in output_locations.items():
            if directory.exists():
                files = []
                for file_path in directory.glob("*"):
                    if file_path.is_file():
                        files.append(
                            {
                                "name": file_path.name,
                                "path": str(file_path),
                                "size_bytes": file_path.stat().st_size,
                                "created_at": datetime.fromtimestamp(
                                    file_path.stat().st_mtime
                                ).isoformat(),
                            }
                        )
                if files:
                    outputs[output_type] = files

        return outputs

    def verify_critical_outputs(self) -> Dict[str, bool]:
        """
        Verify that critical outputs exist and are valid.
        """
        critical_checks = {
            "html_exists": False,
            "csv_exists": False,
            "logs_exist": False,
        }

        # Check HTML
        html_dir = self.project_root / "reports" / "html"
        if html_dir.exists() and list(html_dir.glob("*.html")):
            critical_checks["html_exists"] = True

        # Check CSV
        csv_dir = self.project_root / "csv" / "processed"
        if csv_dir.exists() and list(csv_dir.glob("*.csv")):
            critical_checks["csv_exists"] = True

        # Check logs
        log_dir = self.project_root / "reports" / "logs"
        if log_dir.exists() and list(log_dir.glob("*.log")) or list(log_dir.glob("*.txt")):
            critical_checks["logs_exist"] = True

        return critical_checks


# ========================================================================
# RESULT FORMATTER — Formats results for local agent
# ========================================================================

class ResultFormatter:
    """
    Formats orchestrator execution results into structured format.
    """

    @staticmethod
    def format_cloud_result(
        orchestrator_result: Dict,
        collected_outputs: Dict,
        critical_checks: Dict,
    ) -> Dict:
        """
        Format results into standard cloud agent result format.
        """
        result = {
            "report_id": f"CLOUD_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
            "agent_type": "cloud_agent",
            "executed_at": datetime.utcnow().isoformat() + "Z",
            "orchestrator_execution": {
                "status": orchestrator_result.get("status"),
                "return_code": orchestrator_result.get("return_code"),
                "stdout_length": len(orchestrator_result.get("stdout", "")),
                "stderr_length": len(orchestrator_result.get("stderr", "")),
            },
            "outputs_collected": collected_outputs,
            "critical_outputs_verified": critical_checks,
            "ready_for_local_verification": critical_checks.get("html_exists", False)
            and critical_checks.get("csv_exists", False),
        }

        return result


# ========================================================================
# CLOUD AGENT MAIN CLASS
# ========================================================================

class CloudAgent:
    """
    Main cloud agent: executes orchestrator and returns results.
    """

    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.executor = OrchestratorExecutor(project_root)
        self.collector = OutputCollector(project_root)

    def execute_pipeline(self) -> Dict:
        """
        Main cloud agent execution:
        1. Run orchestrator
        2. Collect outputs
        3. Verify critical outputs
        4. Format results
        5. Return to local agent
        """
        print("\n" + "=" * 70)
        print("CLOUD AGENT — EXECUTING ORCHESTRATOR")
        print("=" * 70)

        # Step 1: Run orchestrator
        print("\n[Step 1/4] Running orchestrator.py...")
        orchestrator_result = self.executor.run_orchestrator()

        # Step 2: Collect outputs
        print("\n[Step 2/4] Collecting outputs...")
        collected_outputs = self.collector.collect_outputs()
        print(f"  → Collected {len(collected_outputs)} output types")

        # Step 3: Verify critical outputs
        print("\n[Step 3/4] Verifying critical outputs...")
        critical_checks = self.collector.verify_critical_outputs()
        print(f"  → Critical checks: {critical_checks}")

        # Step 4: Format results
        print("\n[Step 4/4] Formatting results...")
        result = ResultFormatter.format_cloud_result(
            orchestrator_result, collected_outputs, critical_checks
        )

        print("\n[COMPLETE] Cloud agent execution finished")
        print(f"  Status: {orchestrator_result.get('status')}")
        print(f"  Ready for verification: {result['ready_for_local_verification']}")

        return result


# ========================================================================
# CLOUD AGENT ENDPOINT (for remote invocation)
# ========================================================================

class CloudAgentEndpoint:
    """
    Exposes cloud agent functionality as callable endpoint.
    Used by local agent to invoke cloud agent remotely.
    """

    def __init__(self, project_root: Path):
        self.agent = CloudAgent(project_root)

    def invoke(self) -> Dict:
        """
        Invoke cloud agent and return results.
        """
        return self.agent.execute_pipeline()

    def get_status(self) -> Dict:
        """
        Get current cloud agent status.
        """
        return {
            "status": "ready",
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "project_root": str(self.agent.project_root),
        }


# ========================================================================
# ENTRY POINT
# ========================================================================

if __name__ == "__main__":
    project_root = Path(__file__).resolve().parents[1]

    endpoint = CloudAgentEndpoint(project_root)

    # Check if called with arguments
    if len(sys.argv) > 1:
        if sys.argv[1] == "status":
            result = endpoint.get_status()
        elif sys.argv[1] == "execute":
            result = endpoint.invoke()
        else:
            result = {"error": f"Unknown command: {sys.argv[1]}"}
    else:
        # Default: execute pipeline
        result = endpoint.invoke()

    # Output result as JSON
    print("\n" + "=" * 70)
    print("CLOUD AGENT RESULT")
    print("=" * 70)
    print(json.dumps(result, indent=2))

    # Save result for local agent pickup
    result_file = (
        project_root
        / "coordination"
        / "cloud_results"
        / f"cloud_result_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    )
    result_file.parent.mkdir(parents=True, exist_ok=True)

    with open(result_file, "w") as f:
        json.dump(result, f, indent=2)

    print(f"\nResults saved to: {result_file}")
